// Relational Database Seeder: Station Generator
import { Database } from "../../src/types/database";

type StationInsert = Database["public"]["Tables"]["stations"]["Insert"];

export const INDIAN_STATIONS_DATA = [
  { station_code: "NDLS", station_name: "New Delhi", city: "New Delhi", state: "Delhi" },
  { station_code: "HWH", station_name: "Howrah Jn", city: "Kolkata", state: "West Bengal" },
  { station_code: "BCT", station_name: "Mumbai Central", city: "Mumbai", state: "Maharashtra" },
  { station_code: "MAS", station_name: "Chennai Central", city: "Chennai", state: "Tamil Nadu" },
  { station_code: "SBC", station_name: "KSR Bengaluru", city: "Bengaluru", state: "Karnataka" },
  { station_code: "CNB", station_name: "Kanpur Central", city: "Kanpur", state: "Uttar Pradesh" },
  { station_code: "PNBE", station_name: "Patna Jn", city: "Patna", state: "Bihar" },
  { station_code: "BSB", station_name: "Varanasi Jn", city: "Varanasi", state: "Uttar Pradesh" },
  { station_code: "SDAH", station_name: "Sealdah", city: "Kolkata", state: "West Bengal" },
  { station_code: "CSMT", station_name: "Chhatrapati Shivaji Maharaj Terminus", city: "Mumbai", state: "Maharashtra" },
  { station_code: "SC", station_name: "Secunderabad Jn", city: "Hyderabad", state: "Telangana" },
  { station_code: "PUNE", station_name: "Pune Jn", city: "Pune", state: "Maharashtra" },
  { station_code: "LKO", station_name: "Lucknow Charbagh", city: "Lucknow", state: "Uttar Pradesh" },
  { station_code: "BBS", station_name: "Bhubaneswar", city: "Bhubaneswar", state: "Odisha" },
  { station_code: "RNC", station_name: "Ranchi Jn", city: "Ranchi", state: "Jharkhand" },
  { station_code: "GKP", station_name: "Gorakhpur Jn", city: "Gorakhpur", state: "Uttar Pradesh" },
  { station_code: "JAT", station_name: "Jammu Tawi", city: "Jammu", state: "Jammu & Kashmir" },
  { station_code: "ERS", station_name: "Ernakulam Jn", city: "Kochi", state: "Kerala" },
  { station_code: "ADI", station_name: "Ahmedabad Jn", city: "Ahmedabad", state: "Gujarat" },
  { station_code: "BDTS", station_name: "Bandra Terminus", city: "Mumbai", state: "Maharashtra" },
  { station_code: "MS", station_name: "Chennai Egmore", city: "Chennai", state: "Tamil Nadu" },
  { station_code: "YPR", station_name: "Yesvantpur Jn", city: "Bengaluru", state: "Karnataka" },
  { station_code: "HYB", station_name: "Hyderabad Deccan", city: "Hyderabad", state: "Telangana" },
  { station_code: "JBP", station_name: "Jabalpur Jn", city: "Jabalpur", state: "Madhya Pradesh" },
  { station_code: "BPL", station_name: "Bhopal Jn", city: "Bhopal", state: "Madhya Pradesh" },
  { station_code: "INDB", station_name: "Indore Jn", city: "Indore", state: "Madhya Pradesh" },
  { station_code: "GWL", station_name: "Gwalior Jn", city: "Gwalior", state: "Madhya Pradesh" },
  { station_code: "AGC", station_name: "Agra Cantt", city: "Agra", state: "Uttar Pradesh" },
  { station_code: "DLI", station_name: "Old Delhi", city: "Delhi", state: "Delhi" },
  { station_code: "ANVT", station_name: "Anand Vihar Terminus", city: "Delhi", state: "Delhi" },
  { station_code: "NZM", station_name: "Hazrat Nizamuddin", city: "Delhi", state: "Delhi" },
  { station_code: "HW", station_name: "Haridwar", city: "Haridwar", state: "Uttarakhand" },
  { station_code: "DDN", station_name: "Dehradun", city: "Dehradun", state: "Uttarakhand" },
  { station_code: "ASR", station_name: "Amritsar Jn", city: "Amritsar", state: "Punjab" },
  { station_code: "LDH", station_name: "Ludhiana Jn", city: "Ludhiana", state: "Punjab" },
  { station_code: "CDG", station_name: "Chandigarh", city: "Chandigarh", state: "Chandigarh" },
  { station_code: "KLK", station_name: "Kalka", city: "Kalka", state: "Haryana" },
  { station_code: "UMB", station_name: "Ambala Cantt", city: "Ambala", state: "Haryana" },
  { station_code: "JU", station_name: "Jodhpur Jn", city: "Jodhpur", state: "Rajasthan" },
  { station_code: "JP", station_name: "Jaipur Jn", city: "Jaipur", state: "Rajasthan" },
  { station_code: "BKN", station_name: "Bikaner Jn", city: "Bikaner", state: "Rajasthan" },
  { station_code: "UDZ", station_name: "Udaipur City", city: "Udaipur", state: "Rajasthan" },
  { station_code: "AII", station_name: "Ajmer Jn", city: "Ajmer", state: "Rajasthan" },
  { station_code: "KOTA", station_name: "Kota Jn", city: "Kota", state: "Rajasthan" },
  { station_code: "RTM", station_name: "Ratlam Jn", city: "Ratlam", state: "Madhya Pradesh" },
  { station_code: "BRC", station_name: "Vadodara Jn", city: "Vadodara", state: "Gujarat" },
  { station_code: "ST", station_name: "Surat", city: "Surat", state: "Gujarat" },
  { station_code: "RJT", station_name: "Rajkot Jn", city: "Rajkot", state: "Gujarat" },
  { station_code: "GIMB", station_name: "Gandhidham Jn", city: "Gandhidham", state: "Gujarat" },
  { station_code: "NGP", station_name: "Nagpur Jn", city: "Nagpur", state: "Maharashtra" },
  { station_code: "NED", station_name: "Hazur Sahib Nanded", city: "Nanded", state: "Maharashtra" },
  { station_code: "G", station_name: "Gondia Jn", city: "Gondia", state: "Maharashtra" },
  { station_code: "BSL", station_name: "Bhusaval Jn", city: "Bhusaval", state: "Maharashtra" },
  { station_code: "NK", station_name: "Nashik Road", city: "Nashik", state: "Maharashtra" },
  { station_code: "MMR", station_name: "Manmad Jn", city: "Manmad", state: "Maharashtra" },
  { station_code: "SUR", station_name: "Solapur Jn", city: "Solapur", state: "Maharashtra" },
  { station_code: "UBL", station_name: "SSS Hubballi Jn", city: "Hubli", state: "Karnataka" },
  { station_code: "MYS", station_name: "Mysuru Jn", city: "Mysore", state: "Karnataka" },
  { station_code: "MAQ", station_name: "Mangaluru Central", city: "Mangalore", state: "Karnataka" },
  { station_code: "MAJN", station_name: "Mangaluru Jn", city: "Mangalore", state: "Karnataka" },
  { station_code: "TVC", station_name: "Thiruvananthapuram Central", city: "Trivandrum", state: "Kerala" },
  { station_code: "CLT", station_name: "Kozhikode Main", city: "Calicut", state: "Kerala" },
  { station_code: "ERN", station_name: "Ernakulam Town", city: "Kochi", state: "Kerala" },
  { station_code: "TCR", station_name: "Thrissur", city: "Thrissur", state: "Kerala" },
  { station_code: "CBE", station_name: "Coimbatore Jn", city: "Coimbatore", state: "Tamil Nadu" },
  { station_code: "MDU", station_name: "Madurai Jn", city: "Madurai", state: "Tamil Nadu" },
  { station_code: "TPJ", station_name: "Tiruchchirappalli Jn", city: "Trichy", state: "Tamil Nadu" },
  { station_code: "ED", station_name: "Erode Jn", city: "Erode", state: "Tamil Nadu" },
  { station_code: "SA", station_name: "Salem Jn", city: "Salem", state: "Tamil Nadu" },
  { station_code: "RU", station_name: "Renigunta Jn", city: "Renigunta", state: "Andhra Pradesh" },
  { station_code: "TPTY", station_name: "Tirupati", city: "Tirupati", state: "Andhra Pradesh" },
  { station_code: "BZA", station_name: "Vijayawada Jn", city: "Vijayawada", state: "Andhra Pradesh" },
  { station_code: "VSKP", station_name: "Visakhapatnam", city: "Visakhapatnam", state: "Andhra Pradesh" },
  { station_code: "TIG", station_name: "Titlagarh Jn", city: "Titlagarh", state: "Odisha" },
  { station_code: "ROU", station_name: "Rourkela Jn", city: "Rourkela", state: "Odisha" },
  { station_code: "CTC", station_name: "Cuttack Jn", city: "Cuttack", state: "Odisha" },
  { station_code: "PURI", station_name: "Puri", city: "Puri", state: "Odisha" },
  { station_code: "KGP", station_name: "Kharagpur Jn", city: "Kharagpur", state: "West Bengal" },
  { station_code: "ASN", station_name: "Asansol Jn", city: "Asansol", state: "West Bengal" },
  { station_code: "DGR", station_name: "Durgapur", city: "Durgapur", state: "West Bengal" },
  { station_code: "MLDT", station_name: "Malda Town", city: "Malda", state: "West Bengal" },
  { station_code: "NJP", station_name: "New Jalpaiguri", city: "Siliguri", state: "West Bengal" },
  { station_code: "APDJ", station_name: "Alipurduar Jn", city: "Alipurduar", state: "West Bengal" },
  { station_code: "GHY", station_name: "Guwahati", city: "Guwahati", state: "Assam" },
  { station_code: "KYQ", station_name: "Kamakhya Jn", city: "Guwahati", state: "Assam" },
  { station_code: "DBRG", station_name: "Dibrugarh", city: "Dibrugarh", state: "Assam" },
  { station_code: "TSK", station_name: "Tinsukia Jn", city: "Tinsukia", state: "Assam" },
  { station_code: "MFP", station_name: "Muzaffarpur Jn", city: "Muzaffarpur", state: "Bihar" },
  { station_code: "DBG", station_name: "Darbhanga Jn", city: "Darbhanga", state: "Bihar" },
  { station_code: "GAYA", station_name: "Gaya Jn", city: "Gaya", state: "Bihar" },
  { station_code: "BJU", station_name: "Barauni Jn", city: "Barauni", state: "Bihar" },
  { station_code: "DDU", station_name: "Pt. Deen Dayal Upadhyaya Jn", city: "Mughalsarai", state: "Uttar Pradesh" },
  { station_code: "PRYJ", station_name: "Prayagraj Jn", city: "Allahabad", state: "Uttar Pradesh" },
  { station_code: "VGLJ", station_name: "Virangana Lakshmibai Jhansi Jn", city: "Jhansi", state: "Uttar Pradesh" },
  { station_code: "LJN", station_name: "Lucknow Jn", city: "Lucknow", state: "Uttar Pradesh" },
  { station_code: "GD", station_name: "Gonda Jn", city: "Gonda", state: "Uttar Pradesh" },
  { station_code: "BE", station_name: "Bareilly Jn", city: "Bareilly", state: "Uttar Pradesh" },
  { station_code: "BSAL", station_name: "Bansur", city: "Bansur", state: "Rajasthan" },
  { station_code: "HBJ", station_name: "Habibganj", city: "Bhopal", state: "Madhya Pradesh" },
  { station_code: "SMR", station_name: "Samastipur Jn", city: "Samastipur", state: "Bihar" },
];

export function generateStations(): StationInsert[] {
  const stations: StationInsert[] = [];
  
  for (const s of INDIAN_STATIONS_DATA) {
    stations.push({
      station_code: s.station_code,
      station_name: s.station_name,
      city: s.city,
      state: s.state,
    });
  }

  return stations;
}
